

# This file was *autogenerated* from the file str2m.sage
from sage.all_cmdline import *   # import sage library

_sage_const_114356107 = Integer(114356107); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_300 = Integer(300); _sage_const_2p7 = RealNumber('2.7'); _sage_const_3p0 = RealNumber('3.0'); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3)
from sage.stats.distributions.discrete_gaussian_polynomial import DiscreteGaussianDistributionPolynomialSampler
q=_sage_const_114356107 
k=_sage_const_2 
d=_sage_const_4 
sd=_sage_const_300 
M=_sage_const_2p7 
sd=_sage_const_3p0 
K = CyclotomicField(_sage_const_2 *d, names=('zeta',)); (zeta,) = K._first_ngens(1)
OK = K.ring_of_integers()
sigma=K.automorphisms()
sigma_5=K.hom([zeta**(-_sage_const_1 )])
D = DiscreteGaussianDistributionPolynomialSampler(OK, _sage_const_8 , sd)

def str2m(x,dimension):
    y=matrix(dimension, _sage_const_1 , lambda i, j: OK.random_element(_sage_const_16 ))
    y=y-y
    l=len(x)
    i=_sage_const_0 
    d=_sage_const_0 
    coe=''
    index=''
    operation='+'
    symbol=x[_sage_const_0 ]
    print("dimension:",dimension)
    while i < l:     
        print("i:",i)
        print("symbol:",symbol)
        print("d:",d)
     
        if symbol=='[':
            i+=_sage_const_1 
            symbol=x[i]
            while symbol==' ':
                i+=_sage_const_1 
                symbol=x[i]
            continue
        if(symbol=='+'):
            operation='+'
            i+=_sage_const_1 
            symbol=x[i]
        if(symbol=='-'):
            operation='-' 
            i+=_sage_const_1  
            symbol=x[i]
        while '0' <= symbol <= '9':
            coe += symbol
            i+=_sage_const_1 
            symbol=x[i]
        if coe!='':
            print("coe:",coe)
        if coe!='' and (symbol==' ' or symbol== ']'):
            if(operation=='+'):
                y[d,_sage_const_0 ]+=int(coe)
            else:
                y[d,_sage_const_0 ]+=-int(coe)
            coe=''
        if symbol=='z' or symbol=='e' or symbol=='t' or symbol =='*':
            i+=_sage_const_1 
            symbol=x[i]
        if symbol=='a': # if see zeta
            i+=_sage_const_1 
            symbol=x[i]
            if symbol == '^':
                i+=_sage_const_1 
                symbol=x[i]
                while '0' <= symbol <= '9':
                    index += symbol
                    i+=_sage_const_1 
                    symbol=x[i]
            else:
                index='1'
        if (index!= ''): # do have zeta
            print("coe:",coe)
            if(coe==''):
                coe='1'
            if(operation=='+'):
                y[d,_sage_const_0 ]+=int(coe)*zeta**int(index)
            else:
                y[d,_sage_const_0 ]+=-int(coe)*zeta**int(index) 
            coe=''
            index=''
        # elif (symbol==']'):
       # elif (symbol!='*'): # no zeta
           # if(coe==''):
              #  coe='0'
           # if(operation=='+'):
              #  y[d,0]+=int(coe)
           # else:
              #  y[d,0]+=-int(coe)
           # coe=''

        if symbol=='\n':
            d+=_sage_const_1 
            i+=_sage_const_1 
            symbol=x[i]

        if  i<l-_sage_const_1  and symbol==' ' and x[i-_sage_const_1 ]!= '+' and x[i-_sage_const_1 ]!='-' and x[i-_sage_const_1 ] != ' ' and x[i+_sage_const_1 ]!='+' and x[i+_sage_const_1 ]!= '-':
            d+=_sage_const_1 
          
        if symbol==']':
            if d==dimension-_sage_const_1 :
                if coe=='':
                    break
                else:
                    continue
            else:
                i+=_sage_const_1 
                symbol=x[i]
                continue  
                
        if symbol==' ':
            i+=_sage_const_1 
            symbol=x[i] 
    return y
    
    
a="[         2*zeta^3 + 9*zeta^2 + 9*zeta + 14 zeta^3 + 15*zeta^2 + 15*zeta + 15  11*zeta^3 + 6*zeta^2 + 12*zeta + 8]   " 
b="[ 2*zeta^3 + 9*zeta^2 + 9*zeta + 14]"
c="[14*zeta^3 - zeta^2 + 11*zeta + 13]\n[          -2*zeta^2 + 3*zeta + 16]\n[2*zeta^3 + 9*zeta^2 + 3*zeta + 12]"

print(str2m(a,_sage_const_3 ))
print(str2m(a,_sage_const_3 ).transpose())
print(str2m(b,_sage_const_1 ))
print(str2m(c,_sage_const_3 ))


